### PR TITLE
E2e

### PR DESCRIPTION
**Pull request by martinhbramwell**
Hi Sacha,

This is a preliminary view.  Could I ask you to give it a try?

I have no immediate way to do a cross-platform check, and I'd prefer to get your feedback before I go any further.

Rgds,
Martin

### CODE REVIEW

**Comment by vincro** [comment]
@martinhbramwell What's the current state of play with this? Would you say it is completed?

**Comment by martinhbramwell** [comment]
I have no idea. I have dropped Vulcan entirely.

**Comment by martinhbramwell** [comment]
@vincro 

The only reason I had for this Pull Request was to offer a quick start to anyone who thinks testing for Vulcan might not be such a bad idea.  

There were no takers. No sign of any interest at all.

I left it in a state where it was immediately useable.  I have no idea what has happened since then.

**Comment by vincro** [comment]
@martinhbramwell THANKS =)  I was going to try run with it, and get some of it integrated into a wider testing / example for people to use with Vulcan.

**Comment by SachaG** [comment]
> There were no takers. No sign of any interest at all.

Sorry about that, I can see how that'd be frustrating. It just takes time for me to review PRs, especially when they introduce new elements. I'm sure this will be very useful as a starting point going forward!

**Comment by eric-burel** [comment]
Hi, I am going to close as we probably won't use chimp for e2e testing, with the idea of being as Meteor -independant as possible. We've just setup an example test with Cypress.

Cypress is a bit less optimized for Meteor (basically it won't be able to call Meteor methods, eg for seeding), but it's more standard and incredibly powerful when it comes to actually creating the tests.

**Pull request closed without merging**
