### PR TITLE
Ensure users know to set METEOR_PACKAGE_DIRS in their ${HOME}/.profile

### PR DESCRIPTION
**Pull request by martinhbramwell**
This adds some scripting to append the METEOR_PACKAGE_DIRS export to ${HOME}/.profile if it's not there and update it if there is one there already.

### CODE REVIEW

**Comment by SachaG** [comment]
That's great but for the standard install `export METEOR_PACKAGE_DIRS=${ YOUR VULCAN HOME }/packages;` isn't really necessary? I think it's better to keep things simple imo.

**Comment by martinhbramwell** [comment]
Are you sure?  I was getting an error when I tried to run without that reference.

**Comment by SachaG** [comment]
I'll have to double-check but you're not supposed to get an error.

**Comment by martinhbramwell** [comment]
I noticed the error after rebooting.
When I added the METEOR_PACKAGE_DIRS link to my ~/.profile I could reboot without the error appearing.

**Comment by SachaG** [comment]
What was the error?

**Comment by martinhbramwell** [comment]
Sorry not to have shown the error initially, I was explaining why I added the PACKAGE_DIRS linking, not reporting a bug.  I thought the error was an expected consequence of not having the link, and saw no reason to look any deeper.  Anyway, this is what I am seeing : 

    /home/you/.meteor/packages/meteor-tool/.1.2_2.fkst7p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						    throw(ex);
						    ^
    Error: Fragment "UsersCurrent" registered, but not initialized.
        at getFragment (packages/vulcan:lib/lib/modules/fragments.js:161:11)
        at withCurrentUser (packages/vulcan:core/lib/modules/containers/withCurrentUser.js:15:9)
        at meteorInstall.node_modules.meteor.vulcan:forms.lib.FormWrapper.jsx (packages/vulcan:forms/lib/FormWrapper.jsx:223:16)
        at fileEvaluate (packages/modules-runtime.js:333:9)
        at require (packages/modules-runtime.js:228:16)
        at meteorInstall.node_modules.meteor.vulcan:forms.lib.export.js (packages/vulcan:forms/lib/export.js:1:228)
        at fileEvaluate (packages/modules-runtime.js:333:9)
        at require (packages/modules-runtime.js:228:16)
        at /home/you/projects/Vulcan-Starter/.meteor/local/build/programs/server/packages/vulcan_forms.js:2121:15
        at /home/you/projects/Vulcan-Starter/.meteor/local/build/programs/server/packages/vulcan_forms.js:2127:3
    => Exited with code: 1

**Comment by SachaG** [comment]
I think that's an unrelated issue, let me look into it.

**Comment by eric-burel** [comment]
Closing as we try to minimize the code surface. We expect users to learn advanced Meteor feature for packages alongside Vulcan, and to directly ask questions on the Slack if they feel blocked or support such help script as 3rd party repos.

**Pull request closed without merging**
