### PR TITLE
Cypress end to end tests

### PR DESCRIPTION
**Pull request by loustak**
This PR add tests to the `example-forms` meteor package.
To run them first you have to go in `.meteor/packages` and comment the getting-started line, then uncomment the example-forms line. Next simply run `npm run test` to run them without gui or use `npm run test:gui` to run them inside a simulated browser.

This PR serve as a proof that semantized class names are working for this example of form and datatable.

Note: the test will pass only if the other PR is accepted on the vulcan main repository.

### CODE REVIEW

**Comment by eric-burel** [comment]
Great job! Is there a way to run `meteor add ***` etc. in order to load the correct packages automatically, as we discussed? For example using "exec" in a beforeAll callback or smth like that (I don't know the precise syntax of Cypress for this though)

**Comment by loustak** [comment]
> Great job! Is there a way to run `meteor add ***` etc. in order to load the correct packages automatically, as we discussed? For example using "exec" in a beforeAll callback or smth like that (I don't know the precise syntax of Cypress for this though)

There seems to be no "simple" way of doing this. But I think a cli interface in node should be doable to archieve the task of manipulating the `.meteor/packages` file, this separete project could be realeased as an npm package so other meteor projects could also use it. Should I try to make it?

**Comment by eric-burel** [comment]
The `meteor` CLI is already supposed to do that? What's the blocker that prevents you to implement this with Cypress?

**Comment by loustak** [comment]
As we discusses tests now correctly setup meteor by changing the .meteor/packages files. This takes quite a bit of time trough but now the test should works out of the box.

**Comment by eric-burel** [comment]
Excellent! However you seem to have included the modified ".meteor/packages" in your PR + the backup. Are you sure those files are correctly restaured after you run the test?

**Comment by loustak** [comment]
Fixed (I commited while a test was running, oups...), the .meteor/packages file is changed with only the getting-started line at the end of the file (else running test would modify the file and git would ask to commit the changes).

**Comment by eric-burel** [comment]
:tada:

**Pull request merged**
