### PR TITLE
Use vulcan-ui-bootstrap (issue #50)

### PR DESCRIPTION
**Pull request by kabalin**
Here are the patches for example-forms and example-membership. @SachaG I am not sure if you done example-forum already, if not forum patches will follow here.

### CODE REVIEW

**Comment by kabalin** [comment]
Added patch for `example-forum` without Dropdown and Modal refactoring yet.

**Comment by SachaG** [comment]
> I only managed to resolve the issue by specifying vulcan:ui-bootstrap explicitly in .meteor/packages, i.e.

Yes, I've been running into the same issue. I think it's a problem with Meteor's package management system. 

In this specific case though we *don't* want to add the dependency in the example package's `package.js` files though, since that would mean users wouldn't be able to switch from bootstrap to other UI frameworks without modifying the file. So putting it in `.meteor/packages` is the right move I think.

I'll wait until you're finished with the dropdown/modal stuff to merge. Don't hesitate to ping me on Slack if the dropdown stuff is confusing btw :)

**Comment by kabalin** [comment]
> In this specific case though we don't want to add the dependency in the example package's package.js files though, since that would mean users wouldn't be able to switch from bootstrap to other UI frameworks without modifying the file. So putting it in .meteor/packages is the right move I think.

In fact, I would keep reference to ui-bootstrap in example package's package.js. You know, these packages are "examples" by defintion, someone willing to use other UI framework probably would end up modifying the code anyway. Though, I can remove package.js changes from the patches if you wish.

I looked closer at modal and have got a question. [UsersProfileCheck.jsx](https://github.com/VulcanJS/Vulcan-Starter/blob/master/packages/example-forum/lib/components/users/UsersProfileCheck.jsx) has `Modal.Footer`, while `Components.ModalTrigger`  does not have one. Shall I make ModalTrigger to support footer or move its content to body when migrating to Components.ModalTrigger (or even remove footer content completely)?

**Comment by SachaG** [comment]
> You know, these packages are "examples" by defintion, someone willing to use other UI framework probably would end up modifying the code anyway. 

Yes, that's a good point as well. Let's leave it in `package.js` for now then. 

>  Shall I make ModalTrigger to support footer or move its content to body when migrating to Components.ModalTrigger (or even remove footer content completely)?

Let's remove the footer for now then. We can start simple and always add more features if they're needed in more than one place.

**Comment by kabalin** [comment]
The Modal patch https://github.com/VulcanJS/Vulcan-Starter/pull/51/commits/4b585108895cbb8b43a057a6b92e46ccc4cfcdf9 depends on https://github.com/VulcanJS/Vulcan/pull/1971

**Comment by SachaG** [comment]
Can you push what you have so far? I can take care of the rest :)

**Comment by kabalin** [comment]
@SachaG I did not touch Dropdown code yet to be honest (steep learning curve you know), so there are no pending changes. All I have done so far is pushed, so feel free to take it over from here if  you wish :)

**Comment by SachaG** [comment]
OK, I'll try to do the dropdown stuff today then. Thanks for your work so far!

**Pull request merged**
