### PR TITLE
Add example 'contact us' package

### PR DESCRIPTION
**Pull request by MathiasKandelborg**
I was getting weird babel runtime errors on a new install and a version notch fixed it. It probably has something to do with Meteor. [Here is a link to a Meteor forum post addressing it](https://forums.meteor.com/t/meteor-fails-to-start-after-update/42832)

Add a package that utilizes the VulcanEmail .send function to send a confirmation email when a guest wants contact with the 'site admins'. Useful for websites where the customer wants to be in contact with the 'site admins' (e.g. the HR or support team) 

The mutation check on collection.js simply returns the document. This might be too unsafe.

### CODE REVIEW

**Comment by SachaG** [comment]
Thanks, I'll check it out :)

**Comment by MathiasKandelborg** [comment]
I've updated it with a description. It should be quite easy to get started now :smile:

**Comment by SachaG** [comment]
Sorry, finally had time to look at this!

I like the email integration but I wonder if it wouldn't be better to rethink the example a bit. First of all, I think the naming has some issues, as the collection is called `ContactUsForm`. It should probably be called something like `Messages` instead. 

But beyond that, I think it'd be more valuable to *not* use a collection or SmartForm, and instead use GraphQL mutations to submit the form (even if that might not be how you'd do it in a real world app). This would both match the mental model of how a normal contact form works better; and also showcase something that isn't available in other existing examples. 

I think we can also drop the rate limiting from the example, as that's something that's not really related to Vulcan directly, and I'd rather leave it up to people to find their own implementation. 

I like having the custom validation and custom error in there though, we could keep this but just hook it up to the flash messages instead of SmartForm. 

Oh and as a final note it'd be better to use the email templates system rather than just pass raw HTML to `VulcanEmail.send`. After all the goal of the examples is to showcase Vulcan best practices. 

Hope it makes sense, please let me know if you have any questions!

**Comment by MathiasKandelborg** [comment]
Would `ContactUsMessages` be fine? The point of this package is to use the code as-is and simply plug it into an existing app.

The rate-limiting file can be deleted if some other functionality is needed/used, why shouldn't it be there by default? It's just bonus boilerplate code, it simply makes it easier to use immediately in production.


I tried getting help for the template system but it's really hard to make something. Also, the way these emails are structured is basically the same, just in native template strings. If the documentation actually guided towards making your own functionality and I can figure out how to use templates without spending several hours reading through source code - the original functionality can be used. furthermore, these emails _are_ just raw HTML. They're not supposed to be filled with all kinds of fluff, it's a nice extra for the customer to receive an email and a more effective way for the admin to answer quickly without problems. But, as said, I'll do it if I don't have to spend several hours looking through the source code to troubleshoot problems.


I hope that you are going to reason your arguments. I might come off as rude but you're basically just saying words based on your opinion. There's no reasoning, your message is that I've done most in 
a different way you are thinking and therefore it is wrong and should be changed.

**Comment by MathiasKandelborg** [comment]
Regarding rate-limiting - it's needed no matter what. _Anyone_ is able to send a mail and if there's not rate-limiting from the beginning **I have the moral responsibility when thousands of spam-bots use this exact functionality and it could have been prevented by have rate-limiting on by default - making sure people opt out instead of not thinking about it at all or when it's too late.**

**Comment by SachaG** [comment]
Well, the role of these examples is to teach people about the various features of Vulcan, that's why it's important to use them. Regarding the email thing, if people see plain HTML text strings they might deduce that it's the "correct" way of doing things in Vulcan even though that's not really true. 

That's also why it's not really necessary to make this a drop-in package. The goal is not for people to use as is, but to understand the code and adapt it to their own needs (of course you can also make a separate drop-in plugin and publish it as a Meteor package, that would be great too!). 

For the rate limiting I guess if it was me I wouldn't include it, but it's not a big deal either way. If you feel it's better with it I don't mind.

**Pull request closed without merging**
