### PR TITLE
Update MoviesUsers.jsx

### PR DESCRIPTION
**Pull request by TylerL-uxai**
Forgot ending bracket (causes error on step 13)

### CODE REVIEW

**Comment by SachaG** [comment]
Hmm no I don't think there should be a bracket there? What was the error?

**Comment by tophsic** [comment]
```shell
=> Errors prevented startup:                  
   
   While building for web.browser:
   packages/getting-started/lib/components/movies/MoviesUsers.jsx:9:17: Unexpected token, expected "," (9:17)
   
   While building for os.linux.x86_64:
   packages/getting-started/lib/components/movies/MoviesUsers.jsx:9:17: Unexpected token, expected "," (9:17)
```

**Comment by tophsic** [comment]
My mystake, I just remove `/*` and `*/` instead of all lines `{/*`and `*/}`. I am agree with @SachaG, this PR is not necessary.

**Comment by tobycatlin** [comment]
I did the same thing assuming you only remove the comment tags and leave the curley braces. I had to google the solution, so I think it should be changed to be clearer.

**Comment by SachaG** [comment]
How should it be changed?

**Comment by SachaG** [comment]
How about this?

```
    {/* 
    <div>
      {currentUser && <p>Welcome, {currentUser.displayName} {currentUser.isAdmin && `(admin)`}</p>}
      <Components.AccountsLoginForm redirect={false} /> 
    </div>
    */}
```

**Comment by Apollinaire** [comment]
I think adding the wrapping div is good, you could also add a tip under `// Uncomment contents on #Step13:` 
```
// comments in JSX have the following syntax: {/* <Component /> */} 
```

**Pull request closed without merging**
