### PR TITLE
[WIP] Feature/schema nested objects

### PR DESCRIPTION
**Pull request by eric-burel**
Added a demo nested field (meetingPlace).

Checklist:

- [X] add a demo nested field
- [ ] setup acceptance test for the vulcan:forms package
- [ ] add a script that clean `.meteor/packages` before merge (comment example packages and uncomment getting-started)

### CODE REVIEW

**Comment by Apollinaire** [comment]
Maybe this package could also be a showcase for all form components ? Adding all the other `control` types in the package to have a single place to look to know how to implement every type of input in a SmartForm.

**Comment by SachaG** [comment]
Nice work :) Could you just tweak the PR so that it doesn't change the `"`s, and also keeps `getting-started` as the active package?

**Comment by eric-burel** [comment]
Yep it is not mergeable yet, it will need a few more commits. I'll try to add a script to avoid the need to change the packages file every time we need to merge. I'll check for the `"`, is there currently an eslint rule for this? I use VS Code, I don't know if eslint or prettify is responsible for this.

**Comment by SachaG** [comment]
There are `.editorconfig` and `.eslintrc` files but it's possible the quote thing is not in them. It's hard to track down which file is responsible for what…

**Comment by eric-burel** [comment]
Hi,

I added a script to reset automatically the packages file (comment `examples` and uncomment `getting-started` in `.meteor/packages`) to help developemtn, this could be included in CI or a git hook to be triggered before merge into master. 
I also added an eslint rules for quotes.

Next time I'll add acceptance tests so we can merge this branch.

**Comment by eric-burel** [comment]
This is mergeable I think, I've cleaned up the packages file. I could not write test, I'll just add a test to check that the getting-started is loaded as expected but in another PR.

**Comment by eric-burel** [comment]
Stale

**Pull request closed without merging**
